### ISSUE TITLE
App Crasheing

### ISSUE THREAD

**Issue by delmeluck** [tintinscorpion/Dual-color-Polyline-Animation#9]
MapAnimator.getInstance().animateRoute(mMap, polylineList); generates this error in my emulator any help ?

android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@57da9ab is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
at android.widget.Toast$TN.handleShow(Toast.java:467)
at android.widget.Toast$TN$2.handleMessage(Toast.java:350)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6125)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by tintinscorpion** [comment]
Its fixed now in the latest version 1.1.. Hopefully you can test and provide feedback,
